export const reactPathIndex = "/"
export const reactPathLogin = "/login"
export const reactPathProfile = "/profile"
export const reactPathChangePassword = "/change_password"
export const reactPathUsers = "/users"
export const reactPathUserCreate = "/users/create"

export const apiPathAuthToken = "/api/auth-token/"
export const apiPathUsers = "/api/users/"
export const apiPathUserDetails = "/api/users/me/"
export const apiPathChangePassword = "/api/change_password/"
export const apiPathUserActivate = "/api/users/activate/"
export const apiPathUserCreate = "/api/users/make/"
export const apiPathGroups = "/api/groups/"
export const apiPathTranslations = "/api/translations/"
export const apiPathTranslationSave = "/api/translations/save/"